import { NextResponse } from "next/server";
import { readCollection } from "@/lib/storage";
import { format } from "date-fns";

export async function POST() {
  const [jobs, txns, decisions, routines, goals] = await Promise.all([
    readCollection<Record<string,unknown>>("jobs-ranked"),
    readCollection<Record<string,unknown>>("transactions"),
    readCollection<Record<string,unknown>>("decisions"),
    readCollection<Record<string,unknown>>("routines"),
    readCollection<Record<string,unknown>>("goals"),
  ]);

  const week = format(new Date(), "MMMM do, yyyy");
  const totalSpent = (txns as {amount?:number}[]).filter(t => (t.amount??0) < 0).reduce((s,t) => s + Math.abs(t.amount??0), 0);
  const openDecisions = (decisions as {status?:string}[]).filter(d => d.status === "open").length;
  const activeGoals = (goals as {status?:string}[]).filter(g => g.status === "active").length;
  const trackedJobs = (jobs as {status?:string}[]).filter(j => j.status === "tracked").length;

  const digest = `# Life OS — Weekly Digest
Generated: ${week}

## Career
- Jobs in pipeline: ${jobs.length}
- Tracked / actively pursuing: ${trackedJobs}

## Money
- Total spending this period: £${totalSpent.toFixed(0)}
- Transactions logged: ${txns.length}

## Decisions
- Open decisions: ${openDecisions}
- Total decisions: ${decisions.length}

## Routines
- Active routines configured: ${routines.length}

## Goals
- Active goals: ${activeGoals}
- Total goals: ${goals.length}

---
Generated by Life OS · ${new Date().toISOString()}
`;

  return NextResponse.json({ digest });
}
